plugins:
  postcss-url: {}
  postcss-import: {}
  postcss-normalize: {}
  postcss-preset-env:
    stage: 0
  cssnano:
    preset:
      - 'cssnano-preset-default'
      - discardComments:
          removeAll: true
