plugins:
  postcss-url: {}
  postcss-import: {}
  postcss-normalize:
    forceImport: true
  postcss-apply: {}
  postcss-custom-properties:
    preserve: false
  postcss-preset-env:
    stage: 0
  cssnano:
    preset:
      - 'cssnano-preset-default'
      - discardComments:
          removeAll: true
